### ISSUE TITLE
API is broken (Internal Server Error 500)

### ISSUE THREAD

**Issue by sonicjhon1** [yasinatesim/instagram-media-downloader#3]
The API currently returns (Internal Server Error 500)

Steps to reproduce:
1. Goto https://instagram-fullsize-picture.yasinatesim.vercel.app/api/{any_username}
2. Error 500

![image](https://user-images.githubusercontent.com/41381685/193185799-d81c9645-be44-4af6-9888-6bc50137e88e.png)

**Comment by sonicjhon1** [comment]
Closing as it seems to be resolved.

**Comment by yasinatesim** [comment]
Looks good to me, it works fine
- https://instagram-fullsize-picture.yasinatesim.vercel.app/api/instagram

**Comment by yasinatesim** [comment]
The instagram username should be put after the slash char. For example

- https://instagram-fullsize-picture.yasinatesim.vercel.app/api/instagram
- https://instagram-fullsize-picture.yasinatesim.vercel.app/api/twitter
- https://instagram-fullsize-picture.yasinatesim.vercel.app/api/buhaftanereyegitsem
