### ISSUE TITLE
Add password protect for bots

### ISSUE THREAD

**Issue by yasinatesim** [yasinatesim/instagram-media-downloader#6]

**Comment by Subject-0000** [comment]
so how do we get the admin password ?

**Comment by yasinatesim** [comment]
Hey @kayloko,

There is a `encrypt` function in the project `https://github.com/yasinatesim/instagram-fullsize-picture/blob/master/src/helpers/encrypt.ts`

you can use below steps;

1. create a new password for project. 
```js
console.log(encrypt('<YOUR-ADMIN-PASSWORD>'))
```

for example usage;
https://github.com/yasinatesim/instagram-fullsize-picture/blob/master/pages/_app.tsx#L22

2. Copy your new password in the browser console

3. Update your .env file
```
NEXT_PUBLIC_ADMIN_PASSWORD='<YOUR-ADMIN-PASSWORD>'
```

I had to impose a restriction because the app faced so so many requests

**Comment by yasinatesim** [comment]
Hey @kayloko,

I removed admin password conditions in [app.tsx](https://github.com/yasinatesim/instagram-fullsize-picture/commit/6b18d0490c0209159f15472fb4bb62deeaa95fb3) because I fixed some bugs :) And I added session control system with Firebase - Fşrestore database. For your information
